import React, { useCallback } from 'react'
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useDispatch, useSelector } from 'react-redux';
import { ReducerType } from '../store/store';

const Home: NextPage = () => {

  /* To Mutate Content of Store */
  // const dispatch=useDispatch()
  // useCallback(()=> dispatch(actionCreator()),[dispatch])

  /* To use Store Resourses */
  // useSelector((store:ReducerType)=> store.auth)
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="main bg-dark">Next- Basic Setup with Typescript</div>
    </div>
  );
};

export default Home;
